apiVersion: v1
kind: ConfigMap
metadata:
  name: event-mgmt-config
  namespace: {{ .Values.global.namespace }}
data:
{{- range $key, $val := .Values.global.config }}
  {{ $key }}: {{ $val | quote }}
{{- end }}
